import assert from "node:assert/strict";
import { createRequire } from "node:module";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const typescript = require("typescript");
const here = dirname(fileURLToPath(import.meta.url));
const sourcePath = resolve(here, "../src/subtitleImport.ts");
const source = readFileSync(sourcePath, "utf8");
const output = typescript.transpileModule(source, {
  compilerOptions: {
    module: typescript.ModuleKind.CommonJS,
    target: typescript.ScriptTarget.ES2020,
  },
}).outputText;
const module = { exports: {} };
new Function("require", "module", "exports", output)(require, module, module.exports);
const { parseSubtitles } = module.exports;

const validSrt = parseSubtitles(
  "1\r\n00:00:00,500 --> 00:00:02,250\r\nمرحبا بالعالم\r\n\r\n2\r\n00:00:03 --> 00:00:05\r\nSecond line",
  10,
);
assert.deepEqual(validSrt, [
  { start: 0.5, end: 2.25, text: "مرحبا بالعالم" },
  { start: 3, end: 5, text: "Second line" },
]);

const validVtt = parseSubtitles(
  "WEBVTT\n\nNOTE generated by Clipflow\nthis has --> an arrow\n\n00:01.000 --> 00:02.500 align:start position:50%\n<v Arabic>نص واضح</v>\n\n00:09.000 --> 00:12.000\nclipped at source end",
  10,
);
assert.deepEqual(validVtt, [
  { start: 1, end: 2.5, text: "نص واضح" },
  { start: 9, end: 10, text: "clipped at source end" },
]);

assert.throws(
  () => parseSubtitles("00:04.000 --> 00:03.000\nbackwards", 10),
  /end after it starts/,
);
assert.throws(
  () => parseSubtitles("00:61.000 --> 00:62.000\ninvalid seconds", 100),
  /invalid timestamp/,
);
assert.throws(
  () => parseSubtitles(`00:00.000 --> 00:01.000\n${"line\n".repeat(21)}`, 10),
  /too many text lines/,
);

console.log("subtitleImport tests passed");
